IF EXISTS (SELECT 1 FROM ForumReply) DELETE FROM ForumReply;
IF EXISTS (SELECT 1 FROM ForumPost) DELETE FROM ForumPost;
IF EXISTS (SELECT 1 FROM ForumTopic) DELETE FROM ForumTopic;
IF EXISTS (SELECT 1 FROM ForumTag) DELETE FROM ForumTag;
IF EXISTS (SELECT 1 FROM ForumCategory) DELETE FROM ForumCategory;

IF EXISTS (SELECT 1 FROM UpvoteMovieReview) DELETE FROM UpvoteMovieReview;
IF EXISTS (SELECT 1 FROM DownvoteMovieReview) DELETE FROM DownvoteMovieReview;
IF EXISTS (SELECT 1 FROM MovieReview) DELETE FROM MovieReview;

IF EXISTS (SELECT 1 FROM UpvoteCrewReview) DELETE FROM UpvoteCrewReview;
IF EXISTS (SELECT 1 FROM DownvoteCrewReview) DELETE FROM DownvoteCrewReview;
IF EXISTS (SELECT 1 FROM CrewReview) DELETE FROM CrewReview;

IF EXISTS (SELECT 1 FROM UpvoteSerieReview) DELETE FROM UpvoteSerieReview;
IF EXISTS (SELECT 1 FROM DownvoteSerieReview) DELETE FROM DownvoteSerieReview;
IF EXISTS (SELECT 1 FROM SerieReview) DELETE FROM SerieReview;

IF EXISTS (SELECT 1 FROM UpvoteSeasonReview) DELETE FROM UpvoteSeasonReview;
IF EXISTS (SELECT 1 FROM DownvoteSeasonReview) DELETE FROM DownvoteSeasonReview;
IF EXISTS (SELECT 1 FROM SeasonReview) DELETE FROM SeasonReview;

IF EXISTS (SELECT 1 FROM UpvoteEpisodeReview) DELETE FROM UpvoteEpisodeReview;
IF EXISTS (SELECT 1 FROM DownvoteEpisodeReview) DELETE FROM DownvoteEpisodeReview;
IF EXISTS (SELECT 1 FROM EpisodeReview) DELETE FROM EpisodeReview;

IF EXISTS (SELECT 1 FROM UpvoteActorReview) DELETE FROM UpvoteActorReview;
IF EXISTS (SELECT 1 FROM DownvoteActorReview) DELETE FROM DownvoteActorReview;
IF EXISTS (SELECT 1 FROM ActorReview) DELETE FROM ActorReview;

IF EXISTS (SELECT 1 FROM CastMovie) DELETE FROM CastMovie;
IF EXISTS (SELECT 1 FROM CrewMovie) DELETE FROM CrewMovie;
IF EXISTS (SELECT 1 FROM MovieGenre) DELETE FROM MovieGenre;
IF EXISTS (SELECT 1 FROM Movie) DELETE FROM Movie;

IF EXISTS (SELECT 1 FROM CastSerie) DELETE FROM CastSerie;
IF EXISTS (SELECT 1 FROM CrewSerie) DELETE FROM CrewSerie;
IF EXISTS (SELECT 1 FROM SerieGenre) DELETE FROM SerieGenre;

IF EXISTS (SELECT 1 FROM Episode) DELETE FROM Episode;
IF EXISTS (SELECT 1 FROM Season) DELETE FROM Season;
IF EXISTS (SELECT 1 FROM Serie) DELETE FROM Serie;

IF EXISTS (SELECT 1 FROM Actor) DELETE FROM Actor;
IF EXISTS (SELECT 1 FROM Crew) DELETE FROM Crew;
IF EXISTS (SELECT 1 FROM Genre) DELETE FROM Genre;
IF EXISTS (SELECT 1 FROM [User]) DELETE FROM [User];

DBCC CHECKIDENT ('Movie', RESEED, 0);
DBCC CHECKIDENT ('Serie', RESEED, 0);
DBCC CHECKIDENT ('Season', RESEED, 0);
DBCC CHECKIDENT ('Episode', RESEED, 0);
DBCC CHECKIDENT ('Actor', RESEED, 0);
DBCC CHECKIDENT ('Crew', RESEED, 0);
DBCC CHECKIDENT ('Genre', RESEED, 0);
DBCC CHECKIDENT ('MovieGenre', RESEED, 0);
DBCC CHECKIDENT ('SerieGenre', RESEED, 0);
DBCC CHECKIDENT ('CastMovie', RESEED, 0);
DBCC CHECKIDENT ('CrewMovie', RESEED, 0);
DBCC CHECKIDENT ('CastSerie', RESEED, 0);
DBCC CHECKIDENT ('CrewSerie', RESEED, 0);
DBCC CHECKIDENT ('MovieReview', RESEED, 0);
DBCC CHECKIDENT ('SerieReview', RESEED, 0);
DBCC CHECKIDENT ('SeasonReview', RESEED, 0);
DBCC CHECKIDENT ('EpisodeReview', RESEED, 0);
DBCC CHECKIDENT ('ActorReview', RESEED, 0);
DBCC CHECKIDENT ('CrewReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteMovieReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteMovieReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteSerieReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteSerieReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteSeasonReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteSeasonReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteEpisodeReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteEpisodeReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteActorReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteActorReview', RESEED, 0);
DBCC CHECKIDENT ('UpvoteCrewReview', RESEED, 0);
DBCC CHECKIDENT ('DownvoteCrewReview', RESEED, 0);
DBCC CHECKIDENT ('ForumCategory', RESEED, 0);
DBCC CHECKIDENT ('ForumTag', RESEED, 0);
DBCC CHECKIDENT ('ForumTopic', RESEED, 0);
DBCC CHECKIDENT ('ForumPost', RESEED, 0);
DBCC CHECKIDENT ('ForumReply', RESEED, 0);
DBCC CHECKIDENT ('[User]', RESEED, 0);
