/*******************************************
 * Episode Data
 *******************************************/
-- Episodes - Only insert if table is empty
IF NOT EXISTS (SELECT 1 FROM Episode)
BEGIN
SET
    IDENTITY_INSERT Episode ON;

INSERT INTO
    Episode (
        Id,
        Title,
        Description,
        Duration,
        PhotoSrc,
        PhotoSrcProd,
        TrailerSrc,
        DateAired,
        SeasonId,
        RatingImdb
    )
VALUES
    (
        1,
        'Rebelde S01 E01',
        'Description for Episode 1 of Season 1 in Rebelde.',
        15,
        'http://localhost:4000/images/series/rebelde.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/rebelde.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-01',
        1,
        6.0
    ),
    (
        2,
        'Snowfall S01 E01',
        'Description for Episode 1 of Season 1 in Snowfall.',
        15,
        'http://localhost:4000/images/series/snowfall.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-06-07',
        2,
        5.6
    ),
    (
        3,
        'Snowfall S01 E02',
        'Description for Episode 2 of Season 1 in Snowfall.',
        15,
        'http://localhost:4000/images/series/snowfall.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-07-13',
        2,
        5.2
    ),
    (
        4,
        'Man vs Bee S01 E01',
        'Description for Episode 1 of Season 1 in Man vs Bee.',
        24,
        'http://localhost:4000/images/series/manbee.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-06-11',
        3,
        6.2
    ),
    (
        5,
        'Man vs Bee S01 E02',
        'Description for Episode 2 of Season 1 in Man vs Bee.',
        42,
        'http://localhost:4000/images/series/manbee.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-06-18',
        3,
        5.2
    ),
    (
        6,
        'Man vs Bee S02 E01',
        'Description for Episode 1 of Season 2 in Man vs Bee.',
        31,
        'http://localhost:4000/images/series/manbee.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-01',
        4,
        6.5
    ),
    (
        7,
        'Man vs Bee S01 E02',
        'Description for Episode 2 of Season 2 in Man vs Bee.',
        15,
        'http://localhost:4000/images/series/manbee.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-08',
        4,
        5.1
    ),
    (
        8,
        'Moonknight S01 E01',
        'Description for Episode 1 of Season 1 in Moonknight.',
        39,
        'http://localhost:4000/images/series/moonknight.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-03-30',
        5,
        6.4
    ),
    (
        9,
        'Moonknight S01 E02',
        'Description for Episode 2 of Season 1 in Moonknight.',
        23,
        'http://localhost:4000/images/series/moonknight.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-04-06',
        5,
        6.2
    ),
    (
        10,
        'Moonknight S02 E01',
        'Description for Episode 1 of Season 2 in Moonknight.',
        38,
        'http://localhost:4000/images/series/moonknight.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2024-01-01',
        6,
        5.9
    ),
    (
        11,
        'Moonknight S02 E02',
        'Description for Episode 2 of Season 2 in Moonknight.',
        40,
        'http://localhost:4000/images/series/moonknight.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2024-01-08',
        6,
        5.8
    ),
    (
        12,
        'Peacemaker S01 E01',
        'Description for Episode 1 of Season 1 in Peacemaker.',
        15,
        'http://localhost:4000/images/series/peacemaker.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-01-13',
        7,
        5.6
    ),
    (
        13,
        'Peacemaker S01 E02',
        'Description for Episode 2 of Season 1 in Peacemaker.',
        15,
        'http://localhost:4000/images/series/peacemaker.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-01-20',
        7,
        5.2
    ),
    (
        14,
        'Peacemaker S02 E01',
        'Description for Episode 1 of Season 2 in Peacemaker.',
        39,
        'http://localhost:4000/images/series/peacemaker.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2024-01-01',
        8,
        5.4
    ),
    (
        15,
        'Top Boy S01 E01',
        'Description for Episode 1 of Season 1 in Top Boy.',
        15,
        'http://localhost:4000/images/series/topboy.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-02-20',
        9,
        5.8
    ),
    (
        16,
        'Top Boy S01 E02',
        'Description for Episode 2 of Season 1 in Top Boy.',
        41,
        'http://localhost:4000/images/series/topboy.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-02-27',
        9,
        5.5
    ),
    (
        17,
        'Ganglands S01 E01',
        'Description for Episode 1 of Season 1 in Ganglands.',
        25,
        'http://localhost:4000/images/series/ganglands.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-11-01',
        10,
        5.9
    ),
    (
        18,
        'Ganglands S02 E01',
        'Description for Episode 1 of Season 2 in Ganglands.',
        15,
        'http://localhost:4000/images/series/ganglands.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-01',
        11,
        6.4
    ),
    (
        19,
        'Ozark S01 E01',
        'Description for Episode 1 of Season 1 in Ozark.',
        29,
        'http://localhost:4000/images/series/ozark.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/ozark.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2017-03-21',
        12,
        5.3
    ),
    (
        20,
        'Resident Alien S01 E01',
        'Description for Episode 1 of Season 1 in Resident Alien.',
        36,
        'http://localhost:4000/images/series/alien.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-01-27',
        13,
        5.5
    ),
    (
        21,
        'Resident Alien S01 E02',
        'Description for Episode 2 of Season 1 in Resident Alien.',
        30,
        'http://localhost:4000/images/series/alien.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-02-03',
        13,
        6.0
    ),
    (
        22,
        'Bridgerton S01 E01',
        'Description for Episode 1 of Season 1 in Bridgerton.',
        35,
        'http://localhost:4000/images/series/bridgerton.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2020-12-25',
        14,
        5.4
    ),
    (
        23,
        'Bridgerton S01 E02',
        'Description for Episode 2 of Season 1 in Bridgerton.',
        18,
        'http://localhost:4000/images/series/bridgerton.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-01-01',
        14,
        5.8
    ),
    (
        24,
        'Bridgerton S02 E01',
        'Description for Episode 1 of Season 2 in Bridgerton.',
        31,
        'http://localhost:4000/images/series/bridgerton.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-03-25',
        15,
        5.4
    ),
    (
        25,
        'Superman and Lois S01 E01',
        'Description for Episode 1 of Season 1 in Superman and Lois.',
        16,
        'http://localhost:4000/images/series/superman.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-02-23',
        16,
        5.1
    ),
    (
        26,
        'Superman and Lois S01 E02',
        'Description for Episode 2 of Season 1 in Superman and Lois.',
        15,
        'http://localhost:4000/images/series/superman.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2021-03-02',
        16,
        5.7
    ),
    (
        27,
        'Superman and Lois S02 E01',
        'Description for Episode 1 of Season 2 in Superman and Lois.',
        37,
        'http://localhost:4000/images/series/superman.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-01',
        17,
        5.9
    ),
    (
        28,
        'Attack on Titan S01 E01',
        'Description for Episode 1 of Season 1 in Attack on Titan.',
        35,
        'http://localhost:4000/images/series/aot.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/aot.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2013-04-07',
        18,
        5.3
    ),
    (
        29,
        'Kengan Ashura S01 E01',
        'Description for Episode 1 of Season 1 in Kengan Ashura.',
        20,
        'http://localhost:4000/images/series/baki.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/baki.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2019-12-31',
        19,
        5.8
    ),
    (
        30,
        'Elite S01 E01',
        'Description for Episode 1 of Season 1 in Elite.',
        15,
        'http://localhost:4000/images/series/elite.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2018-10-05',
        20,
        5.0
    ),
    (
        31,
        'Elite S01 E02',
        'Description for Episode 2 of Season 1 in Elite.',
        39,
        'http://localhost:4000/images/series/elite.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2018-10-12',
        20,
        5.1
    ),
    (
        32,
        'Elite S02 E01',
        'Description for Episode 1 of Season 2 in Elite.',
        20,
        'http://localhost:4000/images/series/elite.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2019-09-06',
        21,
        5.8
    ),
    (
        33,
        'Elite S02 E02',
        'Description for Episode 2 of Season 2 in Elite.',
        24,
        'http://localhost:4000/images/series/elite.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2019-09-13',
        21,
        5.7
    ),
    (
        34,
        'The Flash S01 E01',
        'Description for Episode 1 of Season 1 in The Flash.',
        30,
        'http://localhost:4000/images/series/flash.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2014-10-08',
        22,
        5.5
    ),
    (
        35,
        'The Flash S01 E02',
        'Description for Episode 2 of Season 1 in The Flash.',
        44,
        'http://localhost:4000/images/series/flash.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2014-10-15',
        22,
        6.3
    ),
    (
        36,
        'Power Book IV Force S01 E01',
        'Description for Episode 1 of Season 1 in Power Book IV Force.',
        15,
        'http://localhost:4000/images/series/force.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-02-06',
        23,
        5.7
    ),
    (
        37,
        'Power Book IV Force S01 E02',
        'Description for Episode 2 of Season 1 in Power Book IV Force.',
        38,
        'http://localhost:4000/images/series/force.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-02-13',
        23,
        6.5
    ),
    (
        38,
        'Power Book IV Force S02 E01',
        'Description for Episode 1 of Season 2 in Power Book IV Force.',
        26,
        'http://localhost:4000/images/series/force.jpg',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2023-01-01',
        24,
        5.3
    ),
    (
        39,
        'Halo S01 E01',
        'Description for Episode 1 of Season 1 in Halo.',
        30,
        'http://localhost:4000/images/series/halo.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/halo.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2022-03-24',
        25,
        5.2
    ),
    (
        40,
        'The Last Kingdom S01 E01',
        'Description for Episode 1 of Season 1 in The Last Kingdom.',
        29,
        'http://localhost:4000/images/series/kingdom.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2015-10-10',
        26,
        6.4
    ),
    (
        41,
        'The Last Kingdom S01 E02',
        'Description for Episode 2 of Season 1 in The Last Kingdom.',
        15,
        'http://localhost:4000/images/series/kingdom.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2015-10-17',
        26,
        5.2
    ),
    (
        42,
        'Knightfall S01 E01',
        'Description for Episode 1 of Season 1 in Knightfall.',
        15,
        'http://localhost:4000/images/series/knightfall.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2017-12-06',
        27,
        5.1
    ),
    (
        43,
        'Knightfall S01 E02',
        'Description for Episode 2 of Season 1 in Knightfall.',
        16,
        'http://localhost:4000/images/series/knightfall.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2017-12-13',
        27,
        6.3
    ),
    (
        44,
        'Knightfall S02 E01',
        'Description for Episode 1 of Season 2 in Knightfall.',
        18,
        'http://localhost:4000/images/series/knightfall.png',
        'https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png',
        'https://www.youtube.com/embed/D8La5G1DzCM',
        '2019-03-06',
        28,
        5.5
    );

SET
    IDENTITY_INSERT Episode OFF;

END